### ISSUE TITLE
Add Code Metrics

### ISSUE THREAD

**Issue by 7tupel** [ClockworksIO/clci#24]
As a developer (or a PO) I would like to get metrics about the codebase.

**Rationale**
When a codebase grows large it helps to use metrics to reason about both complexity and quality of the code.

**Details**

Those metrics shall include
- [ ] Counting Lines of Code
  - [ ] For the whole codebase
  - [ ] For logical units (i.e. Monorepo)
- [ ] Test Coverage
- [ ] Static code analysis
  - [ ] Code Style - logical issues
  - [ ] Code smells (potentially bad code pattern) 
  - [ ] 

**Technical Details**
The following tools and libraries might be a good start to implement the tasks:
- [linesofcode-bb](https://github.com/matthewdowney/linesofcode-bb) - Count Lines of Code
- [cloverage](https://github.com/cloverage/cloverage) - Clojure test coverage tool
- [kondo](https://github.com/clj-kondo/clj-kondo-bb) - Linter and Analyzer

**Product Details**
Describe non technical details relevant for the product required by this story. I.e. legal requirements. MAY refer to an epic describing the details.
_required if any_

**Acceptance Criteria**
Describe the requirements that must be satisfied to be able to accept the story's implementation.

**Related Issues**
_n.n._

**Stakeholder**
- Developer
- Product Owner
