### ISSUE TITLE
Git tools for Semantic Versioning and Semantic Releases

### ISSUE THREAD

**Issue by 7tupel** [ClockworksIO/clci#9]
As a Developer I would like to use automations based on the git history. Those include

- [x] set the new version number based on the git history and Semantic Versioning
- [x] trigger Github releases with the new version number
- [x] provide the version number for automated builds and deployments

**Rationale**
Keeping track of the correct version number manually can get cumbersome and easily introduces errors. Using a git commit based workflow utilizing conventional commits and semantic versioning can highly reduce errors and cost and helps to keep a clean version history.

**Technical Details**
All tooling related to this issue must be able to be run on bare metal and inside Github Actions.

**Acceptance Criteria**
Each specific story/feature describing the implementation and details of each feature specifies the related ACs.

**Related Issues**

**Stakeholder**
- Developer
- Product Owner
